package StringReverseApp;


/**
* StringReverseApp/StringReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringReverse.idl
* Wednesday, May 6, 2026 5:34:55 PM IST
*/

public interface StringReverseOperations 
{
  String reverse (String str);
} // interface StringReverseOperations
