package StringReverseApp;


/**
* StringReverseApp/StringReverse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringReverse.idl
* Wednesday, May 6, 2026 5:34:55 PM IST
*/

public interface StringReverse extends StringReverseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StringReverse
