package StringReverseApp;

/**
* StringReverseApp/StringReverseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringReverse.idl
* Wednesday, May 6, 2026 5:34:55 PM IST
*/

public final class StringReverseHolder implements org.omg.CORBA.portable.Streamable
{
  public StringReverseApp.StringReverse value = null;

  public StringReverseHolder ()
  {
  }

  public StringReverseHolder (StringReverseApp.StringReverse initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StringReverseApp.StringReverseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StringReverseApp.StringReverseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StringReverseApp.StringReverseHelper.type ();
  }

}
